{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "5c3493b8",
   "metadata": {},
   "outputs": [],
   "source": [
    "import telebot\n",
    "from telebot import types\n",
    "from telebot.types import InlineKeyboardMarkup, InlineKeyboardButton\n",
    "import os\n",
    "import pandas as pd\n",
    "import json\n",
    "import datetime"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8bfe0f43",
   "metadata": {},
   "source": [
    "# Create buttons"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "7390a60c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<telebot.types.ReplyKeyboardMarkup at 0x1bd5c234c40>"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# first level buttons\n",
    "button1 = telebot.types.KeyboardButton(\"Products manager\")\n",
    "button2 = telebot.types.KeyboardButton(\"Customers manager\")\n",
    "keyboard = telebot.types.ReplyKeyboardMarkup(row_width=1,selective=True ,one_time_keyboard=True)\n",
    "keyboard.add(button1, button2)\n",
    "\n",
    "\n",
    "# Create the second level of buttons\n",
    "button1 = telebot.types.KeyboardButton(\"Add product\")\n",
    "button2 = telebot.types.KeyboardButton(\"Edit product\")\n",
    "button3 = telebot.types.KeyboardButton(\"Add product codes\")\n",
    "button4 = telebot.types.KeyboardButton(\"Delete product\")\n",
    "keyboard_product = telebot.types.ReplyKeyboardMarkup(row_width=1,selective=True ,one_time_keyboard=True)\n",
    "keyboard_product.add(button1, button2, button3,button4)\n",
    "\n",
    "\n",
    "# when user click on Add product \n",
    "button1 = telebot.types.KeyboardButton(\"بطاقات ببجي\")\n",
    "button2 = telebot.types.KeyboardButton(\"رايزر جولد\")\n",
    "button3 = telebot.types.KeyboardButton(\"شحن عبر الحساب\")\n",
    "button4 = telebot.types.KeyboardButton(\"خدمات ببجي\")\n",
    "button5 = telebot.types.KeyboardButton(\"ايتونز\")\n",
    "keyboard_category = telebot.types.ReplyKeyboardMarkup(row_width=2,selective=True ,one_time_keyboard=True)\n",
    "keyboard_category.add(button1, button2, button3, button4, button5)\n",
    "\n",
    "\n",
    "\n",
    "# بطاقات ببجي products\n",
    "keyboard_pubg_cards = telebot.types.ReplyKeyboardMarkup(row_width=4,selective=True ,one_time_keyboard=True)\n",
    "# رايزر جولد products\n",
    "keyboard_gold = telebot.types.ReplyKeyboardMarkup(row_width=4,selective=True ,one_time_keyboard=True)\n",
    "# شحن عبر الحساب products\n",
    "keyboard_charge = telebot.types.ReplyKeyboardMarkup(row_width=4,selective=True ,one_time_keyboard=True)\n",
    "# خدمات ببجي products\n",
    "keyboard_pubg_services = telebot.types.ReplyKeyboardMarkup(row_width=4,selective=True ,one_time_keyboard=True)\n",
    "# ايتونز products\n",
    "keyboard_itunes = telebot.types.ReplyKeyboardMarkup(row_width=4,selective=True ,one_time_keyboard=True)\n",
    "\n",
    "\n",
    "# confirm akeyboard_productns\n",
    "button1 = telebot.types.KeyboardButton(\"نعم ، قم بشراء هذا المنتج\")\n",
    "button2 = telebot.types.KeyboardButton(\"لا ، إلغاء الشراء\")\n",
    "keyboard_confirm_purchase = telebot.types.ReplyKeyboardMarkup(row_width=1,selective=True ,one_time_keyboard=True)\n",
    "keyboard_confirm_purchase.add(button1, button2)\n",
    "\n",
    "\n",
    "# when user click on edit product\n",
    "button1 = telebot.types.KeyboardButton(\"Edit Name\")\n",
    "button2 = telebot.types.KeyboardButton(\"Edit Description\")\n",
    "button3 = telebot.types.KeyboardButton(\"Edit Price\")\n",
    "button4 = telebot.types.KeyboardButton(\"Edit Image\")\n",
    "keyboard_edit_product= telebot.types.ReplyKeyboardMarkup(row_width=1,selective=True ,one_time_keyboard=True) \n",
    "keyboard_edit_product.add(button1, button2, button3, button4)\n",
    "\n",
    "\n",
    "# customers \n",
    "button1 = telebot.types.KeyboardButton(\"Edit Balance\")\n",
    "button2 = telebot.types.KeyboardButton(\"Edit Loans\")\n",
    "button3 = telebot.types.KeyboardButton(\"ِShow customers details\")\n",
    "button4 = telebot.types.KeyboardButton(\"ِAdd customer\")\n",
    "keyboard_customers = telebot.types.ReplyKeyboardMarkup(row_width=1,selective=True ,one_time_keyboard=True) \n",
    "keyboard_customers.add(button1, button2, button3, button4)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "089a69db",
   "metadata": {},
   "source": [
    "# check admin"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "e7d0bb41",
   "metadata": {},
   "outputs": [],
   "source": [
    "bot = telebot.TeleBot('6129430590:AAEOVwMOacd1FKikQEXuXnFD5y8De3qKvxY')\n",
    "\n",
    "# Define the admin users who are authorized to access the admin panel\n",
    "ADMIN_USERS = [1077656944]\n",
    "\n",
    "\n",
    "\n",
    "@bot.message_handler(commands=['start'])\n",
    "# Define a decorator function that can be used to restrict access to admin users only\n",
    "def admin_only(func):\n",
    "    def wrapper(message):\n",
    "        with open(\"C:/Users/Shady Emad/Desktop/products bot/Excels/customers.json\", 'r') as file:\n",
    "            customers_data = json.load(file)  \n",
    "            \n",
    "        if message.from_user.id in ADMIN_USERS:\n",
    "            bot.send_message(message.chat.id, \"Hi admin\")\n",
    "            return func(message)\n",
    "        \n",
    "        elif str(message.from_user.id) in customers_data:\n",
    "            bot.send_message(message.chat.id, \"مرحبا ايها العميل\", reply_markup=keyboard_customer)\n",
    "            \n",
    "        else:\n",
    "            bot.send_message(message.chat.id, \"عليك أن تطلب من المسؤول إضافتك إلى مستخدمين البوت حتي تتمكن من استخدامه\")\n",
    "    return wrapper"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6633ba2e",
   "metadata": {},
   "source": [
    "# choose button"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "dfa104a7",
   "metadata": {},
   "outputs": [],
   "source": [
    "@bot.message_handler(func=lambda message: message.text in [\"start\", \"No, start again\"])\n",
    "@admin_only\n",
    "def choose_panel(message):\n",
    "    bot.send_message(message.chat.id,\"How can i help you?\", reply_markup=keyboard)\n",
    "    \n",
    "\n",
    "@bot.message_handler(func=lambda message: message.text == \"Products manager\")\n",
    "@admin_only\n",
    "def open_product_manager(message):\n",
    "    bot.send_message(message.chat.id,\"Products manager is opened\", reply_markup=keyboard_product)\n",
    "    \n",
    "    \n",
    "@bot.message_handler(func=lambda message: message.text == \"Customers manager\")\n",
    "@admin_only\n",
    "def open_customers_manager(message):\n",
    "    bot.send_message(message.chat.id,\"Customers manager is opened\", reply_markup = keyboard_customers)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2d8ff5d2",
   "metadata": {},
   "source": [
    "# Products manager"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "874120ce",
   "metadata": {},
   "source": [
    "# 1. Add product"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "fd223e83",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define a command that allows admin users to add a new product\n",
    "@bot.message_handler(func=lambda message: message.text == \"Add product\")\n",
    "@admin_only\n",
    "\n",
    "def select_category(message):\n",
    "    bot.send_message(message.chat.id, \"Which category you want to add product to?\", reply_markup=keyboard_category)\n",
    "    bot.register_next_step_handler(message, add_product)\n",
    "\n",
    "    \n",
    "def add_product(message):\n",
    "    category_name = message.text\n",
    "    # Ask the user for the product name and price\n",
    "    bot.reply_to(message, \"What's the name of the product you want to add?\")\n",
    "    bot.register_next_step_handler(message, add_product_name, category_name)\n",
    "\n",
    "def add_product_name(message, category_name):\n",
    "    product_name = message.text\n",
    "    bot.reply_to(message, \"What's the description of the product?\")\n",
    "    bot.register_next_step_handler(message, add_product_description, product_name, category_name)\n",
    "    \n",
    "def add_product_description(message, product_name, category_name):\n",
    "    product_description = message.text\n",
    "    bot.reply_to(message, \"What's the price of the product?\")\n",
    "    bot.register_next_step_handler(message, add_product_price, product_name, product_description, category_name)\n",
    "\n",
    "def add_product_price(message, product_name, product_description, category_name):\n",
    "    product_price = int(message.text)\n",
    "    # Ask the user for the product image\n",
    "    bot.register_next_step_handler(message, save_product, product_name, product_description, product_price, category_name)\n",
    "    \n",
    "def save_product(message, product_name, product_description, product_price ,category_name):\n",
    "    try:\n",
    "        products_excel = pd.read_excel(f\"C:/Users/Shady Emad/Desktop/products bot/Excels/categories/{category_name}.xlsx\")\n",
    "        new_product = pd.DataFrame({\"Name\":[product_name],\"Description\": [product_description], \"Price\": [product_price]})\n",
    "        # add the new row to the DataFrame\n",
    "        products_excel = products_excel.append(new_product, ignore_index=True)\n",
    "        # write the DataFrame back to an Excel file\n",
    "        products_excel.to_excel(f\"C:/Users/Shady Emad/Desktop/products bot/Excels/categories/{category_name}.xlsx\", index=False)\n",
    "        \n",
    "        try:\n",
    "            # create product list in json to add codes in it\n",
    "            with open(\"C:/Users/Shady Emad/Desktop/products bot/Excels/products codes.json\", 'r') as file:\n",
    "                product_codes = json.load(file)\n",
    "            # Add new list for new product\n",
    "            product_codes[category_name][product_name]=[]\n",
    "            # Write the updated data back to the JSON file\n",
    "            with open('C:/Users/Shady Emad/Desktop/products bot/Excels/products codes.json', 'w') as file:\n",
    "                json.dump(product_codes, file, indent=4)\n",
    "        \n",
    "        except Exception as e:\n",
    "            # Notify the user that an error occurred\n",
    "            bot.send_message(message.chat.id, f\"An error occurred: {e}\")\n",
    "        \n",
    "        # create products keyboard \n",
    "        if category_name == 'بطاقات ببجي':\n",
    "            button = telebot.types.KeyboardButton(product_name)\n",
    "            keyboard_pubg_cards.add(button)\n",
    "        elif category_name == 'رايزر جولد':\n",
    "            button = telebot.types.KeyboardButton(product_name)\n",
    "            keyboard_gold.add(button)       \n",
    "        elif category_name == 'شحن عبر الحساب':\n",
    "            button = telebot.types.KeyboardButton(product_name)\n",
    "            keyboard_charge.add(button)     \n",
    "        elif category_name == 'خدمات ببجي':\n",
    "            button = telebot.types.KeyboardButton(product_name)\n",
    "            keyboard_pubg_services.add(button)       \n",
    "        elif category_name =='ايتونز':\n",
    "            button = telebot.types.KeyboardButton(product_name)\n",
    "            keyboard_itunes.add(button)       \n",
    "        \n",
    "        \n",
    "        bot.send_message(message.chat.id, \"product is successfully saved\")\n",
    "        \n",
    "    except Exception as e:\n",
    "        # Notify the user that an error occurred\n",
    "        bot.send_message(message.chat.id, f\"An error occurred: {e}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0c9b791c",
   "metadata": {},
   "source": [
    "# 2. Edit product"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "7f10ced4",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Define a command that allows admin users to change the price of an existing product\n",
    "@bot.message_handler(func=lambda message: message.text == \"Edit product\") \n",
    "@admin_only\n",
    "\n",
    "def edit_type(message):\n",
    "    bot.reply_to(message, \"What do you want to edit?\", reply_markup=keyboard_edit_product)  "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "713a4aeb",
   "metadata": {},
   "source": [
    "# Edit Product name"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "be07376b",
   "metadata": {},
   "outputs": [],
   "source": [
    "@bot.message_handler(func=lambda message: message.text == \"Edit Name\") \n",
    "@admin_only\n",
    "\n",
    "def select_category(message):\n",
    "    bot.send_message(message.chat.id, \"Which category do you want to edit product in it?\", reply_markup=keyboard_category)\n",
    "    bot.register_next_step_handler(message, get_old_name)\n",
    "    \n",
    "def get_old_name(message):\n",
    "    category_name = message.text\n",
    "    bot.reply_to(message, \"What's the name of the product that you want to edit\") \n",
    "    bot.register_next_step_handler(message, get_new_name, category_name)\n",
    "    \n",
    "def get_new_name(message, category_name):\n",
    "    old_name = message.text\n",
    "    bot.reply_to(message, \"What's the new name of the product\") \n",
    "    bot.register_next_step_handler(message, change_product_name, old_name, category_name)\n",
    "\n",
    "def change_product_name(message, old_name, category_name):\n",
    "    new_name = message.text\n",
    "    bot.register_next_step_handler(message, save_product_name, old_name, new_name, category_name)\n",
    "\n",
    "\n",
    "def save_product_name(message, old_name, new_name, category_name):\n",
    "    df = pd.read_excel(f\"C:/Users/Shady Emad/Desktop/products bot/Excels/categories/{category_name}.xlsx\")\n",
    "    \n",
    "    mask = df['Name'] == old_name\n",
    "\n",
    "    # Replace the selected values with 'new_value'\n",
    "    df.loc[mask, 'Name'] = new_name\n",
    "\n",
    "    # Save the modified DataFrame back to the Excel file\n",
    "    df.to_excel('products.xlsx', index=False)\n",
    "    \n",
    "    bot.send_message(message.chat.id, \"The porduct name has been changed\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ab07f60e",
   "metadata": {},
   "source": [
    "# Edit product description"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "9aa96bfa",
   "metadata": {},
   "outputs": [],
   "source": [
    "@bot.message_handler(func=lambda message: message.text == \"Edit Description\") \n",
    "@admin_only\n",
    "\n",
    "def select_category(message):\n",
    "    bot.send_message(message.chat.id, \"Which category do you want to edit product in it?\", reply_markup=keyboard_category)\n",
    "    bot.register_next_step_handler(message, get_old_name)\n",
    "\n",
    "def get_old_name(message):\n",
    "    category_name = message.text\n",
    "    bot.reply_to(message, \"What's the name of the product that you want to edit\") \n",
    "    bot.register_next_step_handler(message, get_new_desc, category_name)\n",
    "    \n",
    "def get_new_desc(message, category_name):\n",
    "    product_name = message.text\n",
    "    bot.reply_to(message, \"What's the new description of the product\") \n",
    "    bot.register_next_step_handler(message, change_product_desc, product_name, category_name)\n",
    "\n",
    "def change_product_desc(message, product_name, category_name):\n",
    "    new_desc = message.text\n",
    "    bot.register_next_step_handler(message, save_product_desc, product_name, new_desc, category_name)\n",
    "\n",
    "\n",
    "def save_product_desc(message, product_name, new_desc, category_name):\n",
    "    df = pd.read_excel(f\"C:/Users/Shady Emad/Desktop/products bot/Excels/categories/{category_name}.xlsx\")\n",
    "    \n",
    "    mask = df['Name'] == product_name\n",
    "\n",
    "    # Replace the selected values with 'new_value'\n",
    "    df.loc[mask, 'Description'] = new_desc\n",
    "\n",
    "    # Save the modified DataFrame back to the Excel file\n",
    "    df.to_excel(f\"C:/Users/Shady Emad/Desktop/products bot/Excels/categories/{category_name}.xlsx\", index=False)\n",
    "    \n",
    "    bot.send_message(message.chat.id, \"The porduct description has been changed\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0b03bf28",
   "metadata": {},
   "source": [
    "# Edit product price"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "7327717c",
   "metadata": {},
   "outputs": [],
   "source": [
    "@bot.message_handler(func=lambda message: message.text == \"Edit Price\") \n",
    "@admin_only\n",
    "\n",
    "def select_category(message):\n",
    "    bot.send_message(message.chat.id, \"Which category do you want to edit product in it?\", reply_markup=keyboard_category)\n",
    "    bot.register_next_step_handler(message, get_old_name)\n",
    "\n",
    "def get_old_name(message):\n",
    "    category_name = message.text\n",
    "    bot.reply_to(message, \"What's the name of the product that you want to edit\") \n",
    "    bot.register_next_step_handler(message, get_new_price, category_name)\n",
    "    \n",
    "def get_new_price(message, category_name):\n",
    "    product_name = message.text\n",
    "    bot.reply_to(message, \"What's the new price of the product\") \n",
    "    bot.register_next_step_handler(message, change_product_price, product_name, category_name)\n",
    "\n",
    "def change_product_price(message, product_name, category_name):\n",
    "    new_price = message.text\n",
    "    save_product_price(product_name, new_price, category_name)\n",
    "\n",
    "\n",
    "def save_product_price(ةmessage, product_name, new_price, category_name):\n",
    "    df = pd.read_excel(f\"C:/Users/Shady Emad/Desktop/products bot/Excels/categories/{category_name}.xlsx\", index=False)\n",
    "    \n",
    "    mask = df['Name'] == product_name\n",
    "\n",
    "    # Replace the selected values with 'new_value'\n",
    "    df.loc[mask, 'Price'] = new_price\n",
    "\n",
    "    # Save the modified DataFrame back to the Excel file\n",
    "    df.to_excel(f\"C:/Users/Shady Emad/Desktop/products bot/Excels/categories/{category_name}.xlsx\", index=False)\n",
    "    \n",
    "    bot.send_message(message.chat.id, \"The porduct price has been changed\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "56ca7fce",
   "metadata": {},
   "source": [
    "# Edit product image"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "00004add",
   "metadata": {},
   "outputs": [],
   "source": [
    "@bot.message_handler(func=lambda message: message.text == \"Edit Image\") \n",
    "@admin_only\n",
    "\n",
    "def select_category(message):\n",
    "    bot.send_message(message.chat.id, \"Which category do you want to edit product in it?\", reply_markup=keyboard_category)\n",
    "    bot.register_next_step_handler(message, get_product_name)\n",
    "\n",
    "def get_product_name(message):\n",
    "    category_name = message.text\n",
    "    bot.reply_to(message, \"What's the name of the product that you want to edit\") \n",
    "    bot.register_next_step_handler(message, get_new_image, category_name)\n",
    "    \n",
    "    \n",
    "def get_new_image(message, category_name):\n",
    "    product_name = message.text\n",
    "    bot.reply_to(message, \"Send me the new image of the product\") \n",
    "    bot.register_next_step_handler(message, change_product_image, product_name, category_name)\n",
    "\n",
    "    \n",
    "def change_product_image(message, product_name, category_name):\n",
    "    # Get the file ID of the photo\n",
    "    file_id = message.photo[-1].file_id\n",
    "    # Download the photo from Telegram servers\n",
    "    file_info = bot.get_file(file_id)\n",
    "    file = bot.download_file(file_info.file_path)\n",
    "    # Set the file name for saving\n",
    "    file_name = product_name + '.jpg'\n",
    "    # Set the folder path for saving\n",
    "    folder_path = f\"C:/Users/Shady Emad/Desktop/products bot/products images/{category_name}\"\n",
    "    # Save the image to the folder on the PC\n",
    "    with open(os.path.join(folder_path, file_name), 'wb') as f:\n",
    "        f.write(file)\n",
    "        \n",
    "    bot.reply_to(message, \"Image saved successfully\") "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6a5d0a2d",
   "metadata": {},
   "source": [
    "# Add product codes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "4adf2aaa",
   "metadata": {},
   "outputs": [],
   "source": [
    "@bot.message_handler(func=lambda message: message.text == \"Add product codes\") \n",
    "@admin_only\n",
    "\n",
    "\n",
    "def select_category(message):\n",
    "    bot.send_message(message.chat.id, \"Which category do you want to edit product in it?\", reply_markup=keyboard_category)\n",
    "    global chat_id\n",
    "    chat_id = message.chat.id\n",
    "    bot.register_next_step_handler(message, select_product)\n",
    "\n",
    "\n",
    "def select_product(message):\n",
    "    category_name= message.text\n",
    "    if category_name == 'بطاقات ببجي':\n",
    "        bot.send_message(message.chat.id, \"Which product do you want to add codes for?\", reply_markup=keyboard_pubg_cards)\n",
    "    elif category_name == 'رايزر جولد':\n",
    "        bot.send_message(message.chat.id, \"Which product do you want to add codes for?\", reply_markup=keyboard_gold)     \n",
    "    elif category_name == 'شحن عبر الحساب':\n",
    "        bot.send_message(message.chat.id, \"Which product do you want to add codes for?\", reply_markup=keyboard_charge)     \n",
    "    elif category_name == 'خدمات ببجي':\n",
    "        bot.send_message(message.chat.id, \"Which product do you want to add codes for?\", reply_markup=keyboard_pubg_services)      \n",
    "    else:\n",
    "        pass\n",
    "    bot.register_next_step_handler(message, get_codes,category_name)\n",
    "\n",
    "    \n",
    "def get_codes(message,category_name):\n",
    "    product_name = message.text\n",
    "    bot.send_message(chat_id, \"send codes you want to add\")\n",
    "    bot.register_next_step_handler(message, save_codes, category_name, product_name)\n",
    "\n",
    "    \n",
    "def save_codes(message, category_name, product_name):\n",
    "    codes = message.text.split('\\n')\n",
    "    try:\n",
    "        with open(\"C:/Users/Shady Emad/Desktop/products bot/Excels/products codes.json\", 'r') as file:\n",
    "            product_codes = json.load(file)\n",
    "            \n",
    "        for code in codes:\n",
    "            # Add a new codes to the data dictionary\n",
    "            product_codes[category_name][product_name].append(code)\n",
    "\n",
    "        # Write the updated data back to the JSON file\n",
    "        with open('C:/Users/Shady Emad/Desktop/products bot/Excels/products codes.json', 'w') as file:\n",
    "            json.dump(product_codes, file, indent=4)\n",
    "        \n",
    "        bot.send_message(message.chat.id, \"codes is successfully saved\")\n",
    "    \n",
    "    except Exception as e:\n",
    "        # Notify the user that an error occurred\n",
    "        bot.send_message(message.chat.id, f\"An error occurred: {e}\")   "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "50e78d3b",
   "metadata": {},
   "source": [
    "# 4. Delete product"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "6051cd7e",
   "metadata": {},
   "outputs": [],
   "source": [
    "@bot.message_handler(func=lambda message: message.text == \"Delete product\") \n",
    "@admin_only\n",
    "\n",
    "def select_category(message):\n",
    "    bot.send_message(message.chat.id, \"Which category do you want to delte product from it?\", reply_markup=keyboard_category)\n",
    "    bot.register_next_step_handler(message, select_product_name)\n",
    "    \n",
    "def select_product_name(message):\n",
    "    category_name= message.text\n",
    "    if category_name == 'بطاقات ببجي':\n",
    "        bot.send_message(message.chat.id, \"Which product do you want to delete?\", reply_markup=keyboard_pubg_cards)\n",
    "    elif category_name == 'رايزر جولد':\n",
    "        bot.send_message(message.chat.id, \"Which product do you want to delete?\", reply_markup=keyboard_gold)     \n",
    "    elif category_name == 'شحن عبر الحساب':\n",
    "        bot.send_message(message.chat.id, \"Which product do you want to delete?\", reply_markup=keyboard_charge)     \n",
    "    elif category_name == 'خدمات ببجي':\n",
    "        bot.send_message(message.chat.id, \"Which product do you want to delete?\", reply_markup=keyboard_pubg_services)      \n",
    "    else:\n",
    "        pass\n",
    "    bot.register_next_step_handler(message, delete_data, category_name)\n",
    "    \n",
    "    \n",
    "def delete_data(message,category_name):\n",
    "    product_name = message.text\n",
    "    \n",
    "    # Set the path to the directory containing the image file\n",
    "    folder_path = f\"C:/Users/Shady Emad/Desktop/products bot/products images/{category_name}\"\n",
    "\n",
    "    # Combine the directory path and file name to create the full file path\n",
    "    file_path = os.path.join(folder_path, product_name+'.jpg')\n",
    "\n",
    "    # Check if the file exists before attempting to delete it\n",
    "    if os.path.exists(file_path):\n",
    "        os.remove(file_path)\n",
    "        try: \n",
    "            # Load the Excel file into a Pandas dataframe\n",
    "            df = pd.read_excel(f\"C:/Users/Shady Emad/Desktop/products bot/Excels/categories/{category_name}.xlsx\")\n",
    "            # Select the rows that match the condition\n",
    "            rows_to_drop = df[df['Name'] == product_name].index\n",
    "\n",
    "            # Drop the selected rows\n",
    "            df = df.drop(rows_to_drop)\n",
    "\n",
    "            # Save the updated dataframe back to the Excel file\n",
    "            df.to_excel('products.xlsx', index=False)\n",
    "        \n",
    "\n",
    "            with open(\"C:/Users/Shady Emad/Desktop/products bot/Excels/products codes.json\", 'r') as file:\n",
    "                product_codes = json.load(file)\n",
    "                \n",
    "            del product_codes[category_name][product_name]\n",
    "\n",
    "            # Write the updated data back to the JSON file\n",
    "            with open('C:/Users/Shady Emad/Desktop/products bot/Excels/products codes.json', 'w') as file:\n",
    "                json.dump(product_codes, file, indent=4)\n",
    "        \n",
    "            bot.send_message(message.chat.id, f\"{product_name} delete successfully.\")\n",
    "    \n",
    "        except Exception as e:\n",
    "            # Notify the user that an error occurred\n",
    "            bot.send_message(message.chat.id, f\"An error occurred: {e}\")  \n",
    "        \n",
    "\n",
    "\n",
    "    else:\n",
    "        bot.send_message(message.chat.id, f\"{product_name} does not exist.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c67ea7f5",
   "metadata": {},
   "source": [
    "# *Customers manager"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7b11459a",
   "metadata": {},
   "source": [
    "# 1. Edit Balance"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "50fff894",
   "metadata": {},
   "outputs": [],
   "source": [
    "@bot.message_handler(func=lambda message: message.text == \"Edit Balance\") \n",
    "@admin_only\n",
    "\n",
    "def get_customer_id(message):\n",
    "    bot.reply_to(message, \"What's the ID of the customer?\") \n",
    "    bot.register_next_step_handler(message, get_new_balance)\n",
    "    \n",
    "def get_new_balance(message):\n",
    "    customer_id = str(message.text)\n",
    "    bot.reply_to(message, \"What's the new balance?\") \n",
    "    bot.register_next_step_handler(message, save_balance, customer_id)\n",
    "    \n",
    "def save_balance(message, customer_id):\n",
    "    new_balance = message.text\n",
    "    \n",
    "    try:\n",
    "        with open(\"C:/Users/Shady Emad/Desktop/products bot/Excels/customers.json\", 'r') as file:\n",
    "            customers_data = json.load(file)  \n",
    "        customers_data[customer_id]['balance'] = new_balance\n",
    "        # write the updated data to the JSON file\n",
    "        with open(\"C:/Users/Shady Emad/Desktop/products bot/Excels/customers.json\", 'w') as file:\n",
    "            json.dump(customers_data, file, indent=4)\n",
    "            \n",
    "        bot.send_message(message.chat.id, \"The new balance has been saved successfully\")\n",
    "        \n",
    "    except Exception as e:\n",
    "        # Notify the user that an error occurred\n",
    "        bot.send_message(message.chat.id, f\"An error occurred: {e}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "76470f9b",
   "metadata": {},
   "source": [
    "# 2. Edit loan"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "ec3f042d",
   "metadata": {},
   "outputs": [],
   "source": [
    "@bot.message_handler(func=lambda message: message.text == \"Edit Loans\") \n",
    "@admin_only\n",
    "\n",
    "def get_customer_id(message):\n",
    "    bot.reply_to(message, \"What's the ID of the customer?\") \n",
    "    bot.register_next_step_handler(message, get_new_loan)\n",
    "    \n",
    "def get_new_loan(message):\n",
    "    customer_id = message.text\n",
    "    bot.reply_to(message, \"What's the new Loan?\") \n",
    "    bot.register_next_step_handler(message, save_loan, customer_id)\n",
    "    \n",
    "def save_loan(message, customer_id):\n",
    "    new_loan = message.text\n",
    "    \n",
    "    try:\n",
    "        with open(\"C:/Users/Shady Emad/Desktop/products bot/Excels/customers.json\", 'r') as file:\n",
    "            customers_data = json.load(file)  \n",
    "        user = customers_data[customer_id]\n",
    "        user['loan'] = new_loan\n",
    "        # write the updated data to the JSON file\n",
    "        with open(\"C:/Users/Shady Emad/Desktop/products bot/Excels/customers.json\", 'w') as file:\n",
    "            json.dump(customers_data, file, indent=4)\n",
    "            \n",
    "        bot.send_message(message.chat.id, \"The new loan has been saved successfully\")\n",
    "        \n",
    "            \n",
    "    except Exception as e:\n",
    "        # Notify the user that an error occurred\n",
    "        bot.send_message(message.chat.id, f\"An error occurred: {e}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2def4d81",
   "metadata": {},
   "source": [
    "# 3. ِAdd customer"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "5c71b17f",
   "metadata": {},
   "outputs": [],
   "source": [
    "@bot.message_handler(func=lambda message: message.text == \"ِAdd customer\") \n",
    "@admin_only\n",
    "\n",
    "def get_customer_id(message):\n",
    "    bot.reply_to(message, \"What's the ID of the customer?\") \n",
    "    bot.register_next_step_handler(message, get_customer_balance)\n",
    "\n",
    "def get_customer_balance(message):\n",
    "    customer_id = message.text\n",
    "    bot.reply_to(message, \"What's the Balance of the customer?\") \n",
    "    bot.register_next_step_handler(message, get_customer_loan, customer_id)\n",
    "\n",
    "def get_customer_loan(message, customer_id):\n",
    "    customer_balance = message.text\n",
    "    bot.reply_to(message, \"What's the Loan of the customer?\") \n",
    "    bot.register_next_step_handler(message, save_customer, customer_id, customer_balance)\n",
    "    \n",
    "def save_customer(message, customer_id, customer_balance):\n",
    "    customer_loan = message.text\n",
    "    try:\n",
    "        with open(\"C:/Users/Shady Emad/Desktop/products bot/Excels/customers.json\", 'r') as file:\n",
    "            customers_data = json.load(file)\n",
    "\n",
    "        # Add a new user to the data dictionary\n",
    "        customers_data[customer_id] = {\n",
    "        'balance': int(customer_balance),\n",
    "        'loan': int(customer_loan),\n",
    "        'purchases': []\n",
    "        }\n",
    "\n",
    "        # Write the updated data back to the JSON file\n",
    "        with open('C:/Users/Shady Emad/Desktop/products bot/Excels/customers.json', 'w') as file:\n",
    "            json.dump(customers_data, file, indent=4)   \n",
    "\n",
    "            \n",
    "        bot.send_message(message.chat.id, \"Customer data is successfully saved\")\n",
    "        \n",
    "    except Exception as e:\n",
    "        # Notify the user that an error occurred\n",
    "        bot.send_message(message.chat.id, f\"An error occurred: {e}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b824b153",
   "metadata": {},
   "source": [
    "# 4. Show customers details"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "43c48d4b",
   "metadata": {},
   "outputs": [],
   "source": [
    "@bot.message_handler(func=lambda message: message.text == \"ِShow customers details\") \n",
    "@admin_only\n",
    "\n",
    "def get_customer_id(message):\n",
    "    bot.reply_to(message, \"What's the ID of the customer?\") \n",
    "    bot.register_next_step_handler(message, show_details)\n",
    "    \n",
    "\n",
    "def show_details(message):\n",
    "    customer_id = message.text\n",
    "    \n",
    "    try:\n",
    "        with open(\"C:/Users/Shady Emad/Desktop/products bot/Excels/customers.json\", 'r') as file:\n",
    "            customers_data = json.load(file)\n",
    "        \n",
    "        user = customers_data[customer_id]\n",
    "        bot.send_message(message.chat.id, f\"The customer ID: {customer_id}\"\n",
    "                                          f\"\\n\\n Balance: {user['balance']}\"\n",
    "                                          f\"\\n Loan: {user['loan']}\")\n",
    "    \n",
    "    except Exception as e:\n",
    "        bot.send_message(message.chat.id, f\"An error occurred: {e}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ecd6ecee",
   "metadata": {},
   "source": [
    "# Users:"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a9e5d49f",
   "metadata": {},
   "source": [
    "# 1. Create buttons"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "fad703ad",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<telebot.types.ReplyKeyboardMarkup at 0x1bd5af03e80>"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Create the first level of buttons\n",
    "button1 = telebot.types.KeyboardButton(\"شحن االرصيد\")\n",
    "button2 = telebot.types.KeyboardButton(\"المنتجات\")\n",
    "button3 = telebot.types.KeyboardButton(\"رصيدي\")\n",
    "button4 = telebot.types.KeyboardButton(\"سجل المشتريات\")\n",
    "button5 = telebot.types.KeyboardButton(\"help\")\n",
    "keyboard_customer = telebot.types.ReplyKeyboardMarkup(row_width=2,selective=True ,one_time_keyboard=True)\n",
    "keyboard_customer.add(button1, button2, button3, button4, button5)\n",
    "\n",
    "\n",
    "# products categories\n",
    "button1 = telebot.types.KeyboardButton(\"بطاقات ببجي\")\n",
    "button2 = telebot.types.KeyboardButton(\"رايزر جولد\")\n",
    "button3 = telebot.types.KeyboardButton(\"شحن عبر الحساب\")\n",
    "button4 = telebot.types.KeyboardButton(\"خدمات ببجي\")\n",
    "button5 = telebot.types.KeyboardButton(\"ايتونز\")\n",
    "keyboard_category = telebot.types.ReplyKeyboardMarkup(row_width=2,selective=True ,one_time_keyboard=True)\n",
    "keyboard_category.add(button1, button2, button3, button4, button5)\n",
    "\n",
    "\n",
    "# products categories\n",
    "keyboard_category = telebot.types.ReplyKeyboardMarkup(row_width=2,selective=True ,one_time_keyboard=True)\n",
    "keyboard_category.add(button1, button2, button3, button4, button5)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5a5492cd",
   "metadata": {},
   "source": [
    "# شحن االرصيد"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "4091b083",
   "metadata": {},
   "outputs": [],
   "source": [
    "@bot.message_handler(func=lambda message: message.text == \"شحن االرصيد\")\n",
    "def handel_charge_balance(message):\n",
    "    bot.send_message(message.chat.id,\"لشحن الرصيد تواصل مع هذا الحساب\")\n",
    "    bot.send_message(message.chat.id,\"https://t.me/ShaadyEmad\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "236143ac",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "96e991e6",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "id": "40aa3221",
   "metadata": {},
   "source": [
    "# المنتجات"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "e8507701",
   "metadata": {},
   "outputs": [],
   "source": [
    "@bot.message_handler(func=lambda message: message.text == \"المنتجات\")\n",
    "def get_category(message):\n",
    "    bot.send_message(message.chat.id,\"الفئات المتوفرة\", reply_markup=keyboard_category)\n",
    "    bot.register_next_step_handler(message, send_products)\n",
    "\n",
    "    \n",
    "def send_products(message):\n",
    "    category_name = message.text\n",
    "    global products_df\n",
    "    if category_name == 'بطاقات ببجي':\n",
    "        bot.send_message(message.chat.id,\"المنتجات المتوفرة\", reply_markup=keyboard_pubg_cards)\n",
    "        products_df = pd.read_excel(\"C:/Users/Shady Emad/Desktop/products bot/Excels/categories/بطاقات ببجي.xlsx\")\n",
    "\n",
    "    elif category_name == 'رايزر جولد':\n",
    "        bot.send_message(message.chat.id,\"المنتجات المتوفرة\", reply_markup=keyboard_gold)\n",
    "        products_df = pd.read_excel(\"C:/Users/Shady Emad/Desktop/products bot/Excels/categories/رايزر جولد.xlsx\")\n",
    "        \n",
    "    elif category_name == 'شحن عبر الحساب':\n",
    "        bot.send_message(message.chat.id,\"المنتجات المتوفرة\", reply_markup=keyboard_charge)\n",
    "        products_df = pd.read_excel(\"C:/Users/Shady Emad/Desktop/products bot/Excels/categories/شحن عبر الحساب.xlsx\")\n",
    "    \n",
    "    elif category_name == 'خدمات ببجي':\n",
    "        bot.send_message(message.chat.id,\"المنتجات المتوفرة\", reply_markup=keyboard_pubg_services)\n",
    "        products_df = pd.read_excel(\"C:/Users/Shady Emad/Desktop/products bot/Excels/categories/خدمات ببجي.xlsx\")\n",
    "     \n",
    "    elif category_name =='ايتونز':\n",
    "        bot.send_message(message.chat.id,\"المنتجات المتوفرة\", reply_markup=keyboard_itunes)\n",
    "        products_df = pd.read_excel(\"C:/Users/Shady Emad/Desktop/products bot/Excels/categories/ايتونز.xlsx\")\n",
    "        \n",
    "    bot.register_next_step_handler(message, show_product_details, category_name)\n",
    "    \n",
    "    \n",
    "def show_product_details(message, category_name):\n",
    "    global products_df\n",
    "    product_name = message.text\n",
    "    product_row = products_df.loc[products_df['Name'] == product_name]\n",
    "    \n",
    "    msg = f\" المنتج : {product_name} \\n\"\n",
    "    msg+= f\"الوصف : {product_row.iloc[0]['Description']} \\n\"\n",
    "    msg+= f\"السعر : {product_row.iloc[0]['Price']}\"\n",
    "    bot.send_message(message.chat.id, msg)\n",
    "    \n",
    "    bot.send_message(message.chat.id, \"هل تريد شراء هذا المنتج؟\", reply_markup=keyboard_confirm_purchase)\n",
    "    bot.register_next_step_handler(message, confrim_purchase, product_row, category_name, product_name)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2df72a17",
   "metadata": {},
   "source": [
    "# confirm purchase"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "8e5e0289",
   "metadata": {},
   "outputs": [],
   "source": [
    "def confrim_purchase(message, product_row, category_name, product_name):\n",
    "    if message.text == 'نعم ، قم بشراء هذا المنتجt':\n",
    "        global products_df\n",
    "        \n",
    "        # access product codes file\n",
    "        with open(\"C:/Users/Shady Emad/Desktop/products bot/Excels/products codes.json\", 'r') as file:\n",
    "            product_codes = json.load(file)\n",
    "            \n",
    "        # read customers JSON file\n",
    "        with open(\"C:/Users/Shady Emad/Desktop/products bot/Excels/customers.json\", 'r') as file:\n",
    "            customers_data = json.load(file) \n",
    "            \n",
    "        if len(product_codes[category_name][product_name]) != 0 :\n",
    "            customer_id = str(message.chat.id)\n",
    "            if customers_data[customer_id]['balance'] >= int(product_row.iloc[0]['Price']): \n",
    "                try:\n",
    "                    customers_data[customer_id]['balance'] -= int(product_row.iloc[0]['Price'])   # remove the product price from customer balance\n",
    "                    \n",
    "                    \n",
    "                    # get the product code\n",
    "                    code = product_codes[category_name][product_name]    # access product codes list\n",
    "                    bot.send_message(message.chat.id, code[0])    # send first code in list\n",
    "                    product_codes[category_name][product_name].pop(0)\n",
    "                    \n",
    "\n",
    "                    # Add this purchase to customers JSON file\n",
    "                    customers_data[customer_id]['purchases'].append([product_name, int(product_row.iloc[0]['Price'])])\n",
    "\n",
    "\n",
    "                    # write the updated data to the customers JSON file\n",
    "                    with open(\"C:/Users/Shady Emad/Desktop/products bot/Excels/customers.json\", 'w') as file:\n",
    "                        json.dump(customers_data, file, indent=4)\n",
    "                        \n",
    "                    with open(\"C:/Users/Shady Emad/Desktop/products bot/Excels/products codes.json\", 'w') as file:\n",
    "                        json.dump(product_codes, file, indent=4)\n",
    "\n",
    "                except Exception as e:\n",
    "                    # Notify the user that an error occurred\n",
    "                    bot.send_message(message.chat.id, f\"An error occurred: {e}\")\n",
    "                    \n",
    "                    \n",
    "            else:\n",
    "                bot.send_message(message.chat.id, \"آسف ليس لديك رصيد كافي لشراء هذا المنتج\")\n",
    "                \n",
    "        else:\n",
    "            bot.send_message(message.chat.id, \"عذرا هذا المنتج غير متوفر الآن\")\n",
    "            \n",
    "    elif message.text =='لا ، إلغاء الشراء':\n",
    "        bot.send_message(message.chat.id, \"مرحبا ايها العميل\", reply_markup=keyboard_customer)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "fdeca63c",
   "metadata": {},
   "source": [
    "# رصيدي"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "49fb5c84",
   "metadata": {},
   "outputs": [],
   "source": [
    "@bot.message_handler(func=lambda message: message.text == \"رصيدي\")\n",
    "def send_customer_balance(message):\n",
    "    try:\n",
    "        with open(\"C:/Users/Shady Emad/Desktop/products bot/Excels/customers.json\", 'r') as file:\n",
    "            customers_data = json.load(file)\n",
    "            \n",
    "        user_id = str(message.from_user.id)\n",
    "            \n",
    "        user = customers_data[user_id]\n",
    "            \n",
    "        bot.send_message(message.chat.id, f\"رصيدك: {user['balance']}\" \n",
    "                                          f\"\\n دينك: {user['loan']}\")\n",
    "        \n",
    "    except Exception as e:\n",
    "        # Notify the user that an error occurred\n",
    "        bot.send_message(message.chat.id, f\"An error occurred: {e}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f07597a9",
   "metadata": {},
   "source": [
    "# سجل المشتريات"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "f16f9222",
   "metadata": {},
   "outputs": [],
   "source": [
    "@bot.message_handler(func=lambda message: message.text == \"سجل المشتريات\")\n",
    "def send_last_purchases(message):\n",
    "    try:\n",
    "        with open(\"C:/Users/Shady Emad/Desktop/products bot/Excels/customers.json\", 'r') as file:\n",
    "            customers_data = json.load(file)\n",
    "            \n",
    "        user_id = str(message.chat.id)\n",
    "        for purchase in customers_data[user_id]['purchases']:\n",
    "            bot.send_message(message.chat.id, f\"{purchase[0]} , {purchase[1]}\")\n",
    "        \n",
    "    except Exception as e:\n",
    "        # Notify the user that an error occurred\n",
    "        bot.send_message(message.chat.id, f\"An error occurred: {e}\")\n",
    "    "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c5981ba4",
   "metadata": {},
   "source": [
    "# help"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "d3adc2fe",
   "metadata": {},
   "outputs": [],
   "source": [
    "@bot.message_handler(func=lambda message: message.text == \"help\")\n",
    "def send_help(message):\n",
    "    bot.send_message(message.chat.id, \"إذا كنت بحاجة إلى أي مساعدة ، أرسل رسالة لهذا الحساب\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4bb6a6bc",
   "metadata": {
    "scrolled": false
   },
   "outputs": [],
   "source": [
    "bot.polling()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
